# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a72389e6fbac0f69b6930336fa9b1daee8dc8566d816309c37284d99582539daf00c24b7b0dfd9ae863150121f16346f2198cd98bef86fab712930c00e74967c

test:
  secret_key_base: f8d611969e600f3960df095887b3befa2ea8b9f168ed30d0de39c845139caa0ef4770da294d1f4fbc160dea986cd4aa97c0b7cd3d6a259ce90d2a5f47b4bbd81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
