# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a98d95dd10cd4a65baf97bb1300249e17d994e02f906818163c1cae8164830b845c82394e164d076edac601cf151ff3a46e3b1e1f271720a530021a6a287dce

test:
  secret_key_base: f58cfc67b7c80dea2843b7e0e0469d53d1df72783e6b9c9ee3fcce8c8a438fb233e8c1bd4e723a6a08580b010f83d215046cabec366dcee3608a2b513b33a829

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
