# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6091fddad3c2967011cbeed66f208c6ea1aa7336f06ac91fd5a1b2520935c56ca09035c4c4efa98460d9e43810a309ed510d0196c948daff3534a51233a9c807

test:
  secret_key_base: 890528805febabee555165aed15b194bb81b93f8160cfd3f69ea6e3ab3c919666327ad03ef4a8875f16fbafdfbf6d0b232c40eabbdc915ea746a1cbcb602152e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
