# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85bc6e2fc251209f567bbf8a033c0d249fff1995b509496356970152b26634164ea8bc88c6a4574eaaea76c50d9786738a8e1248b403b472fa310c793cde5c4f

test:
  secret_key_base: a95a2fe32a9386bf1f3618fbf4ec8959b6895169aba5a71b3814733f8985e61448309eefa41ae63e7614b8ac07dcf5b201bfecab24792a336e019d0d4c42ecae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
